[package]
name = "nylon-ring-host"
version = "0.1.0"
edition = "2021"

[dependencies]
nylon-ring = { path = "../nylon-ring" }
tokio = { version = "1.0", features = ["full"] }
libloading = "0.9"
thiserror = "2"
log = "0.4"
dashmap = "6.1"
