[package]
name = "ex-nyring-plugin"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
nylon-ring = { path = "../../crates/nylon-ring" }
tokio = { version = "1", features = ["rt", "rt-multi-thread", "time"] }
